---
#
# Les premiers items en commentaires représente un exemple de la structure des données complète pour créer cette objet.
#
# controller_credentials:
# - name: gitlab
#   # new_name: gitlab V2
#   copy_from: github
#   description: Credentials for GitLab
#   organization: Default   # Organization this Credential belongs to. If provided on creation, do not give either user or team.
#   credential_type: Source Control
#   inputs:
#     username: person
#     password: password
#   # user: "DemoUser"  # User that should own this credential. If provided, do not give either team or organization.
#   # team: "DemoTeam"  # Team that should own this credential. If provided, do not give either user or organization.
#   state: present
#   update_secrets: false

# - name: localuser
#   description: Machine Credential example with become_method input
#   credential_type: Machine
#   inputs:
#     username: localuser
#     password: password
#     become_method: sudo
#
# -------------------------------------------------------------------------------------------------------------------------------

controller_credentials:  # À décommenter au besoin...
  - name: "Vault Password Generic"
    description: "Pour tous les fichier de Voutes durant la Dev. Comme pour Admin."
    credential_type: "Vault"
    organization: "Ville de Quebec"
    inputs:
      vault_id: ''
      vault_password: "{{ vault_credentials_passwords.vault_password_generic }}"

  - name: "Global SSH Ansible User Credential"
    description: "User \"Ansible\" avec connexion avec LA clé SSH global. (Devrait fonctionner seulement dans les clients qui ont reçu la clé public)"
    credential_type: "Machine"
    organization: "Ville de Quebec"
    inputs:
      become_method: sudo
      become_username: ''
      ssh_key_data: "{{ lookup('ansible.builtin.file', '/home/.ssh/id_rsa') }}"
      username: ansible

  - name: "AzureVDQ_RHAAP_User"
    description: ""
    credential_type: "Source Control"
    organization: "Ville de Quebec"
    inputs:
      password: "{{ vault_credentials_passwords.azureVDQ__RHAAP }}"
      username: User

  - name: "Satellite-dodo"
    description: "Satellite for ADM-ID203290"
    credential_type: "Red Hat Satellite 6"
    organization: "Ville de Quebec"
    inputs:
      host: https://satelliteHost.local/
      password: "{{ vault_credentials_passwords.satellite_dodo }}"
      username: ADM-ID203290

  - name: "Satellite-User2"
    description: "Satellite pour User2"
    credential_type: "Red Hat Satellite 6"
    organization: "Ville de Quebec"
    inputs:
      host: https://satelliteHost.local/
      password: "{{ vault_credentials_passwords.satellite_User2 }}"
      username: User2

...
