---
#
# Les premiers items en commentaires représente un exemple de la structure des données complète pour créer cette objet.
#
# controller_hosts:
#   - name: "localhost"
#     # new_name: "localhost V2"
#     description: ""
#     inventory: "Demo Inventory"
#     enabled: true
#     variables:
#       ansible_connection: local
#       ansible_python_interpreter: !unsafe '{{ ansible_playbook_python }}'
#     state: present
#
# -------------------------------------------------------------------------------------------------------------------------------

# controller_hosts:  # À décommenter au besoin...

...
